version: '3'

services:
  drawio:
    build: .
    ports:
      - "8080:8080"
      - "9229:9229"
    expose:
      - "9229"
    volumes:
      - ./src/main/webapp/plugins:/usr/local/tomcat/webapps/draw/plugins
